---
name: Terraform Force Unlock
on:
  workflow_dispatch:
    inputs:
      lock_id:
        description: 'Terraform Lock ID to force unlock'
        required: true
        type: string

jobs:
  plan:
      name: Plan with Terraform
      runs-on:
        self-hosted
      concurrency: test-tfstate
      environment: alzcbg-test-plan
      permissions:
        id-token: write
        contents: read
      env:
        ARM_CLIENT_ID: "${{ vars.AZURE_CLIENT_ID }}"
        ARM_SUBSCRIPTION_ID: "${{ vars.AZURE_SUBSCRIPTION_ID }}"
        ARM_TENANT_ID: "${{ vars.AZURE_TENANT_ID }}"
        ARM_USE_AZUREAD: true
        ARM_USE_OIDC: true

  unlock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7 # or your preferred version

      - name: Terraform Init
        run: |
          terraform \
          -chdir="${{inputs.root_module_folder_relative_path}}" \
          init \
          -backend-config="resource_group_name=${{vars.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" \
          -backend-config="storage_account_name=${{vars.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" \
          -backend-config="container_name=${{vars.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}" \
          -backend-config="key=terraform.tfstate"

      - name: Force Unlock Terraform State
        run: terraform force-unlock -force ${{ github.event.inputs.lock_id }}