---
name: Terraform Force Unlock
on:
  workflow_dispatch:
    inputs:
      lock_id:
        description: 'Terraform Lock ID to force unlock'
        required: true
        type: string

jobs:
  unlock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7 # or your preferred version

      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name=rg-alzcbg-test-state-germanywestcentral-001" \
                            -backend-config="storage_account_name=stoalztesger001iirg" \
                            -backend-config="container_name=test-tfstate" \
                            -backend-config="key=terraform.tfstate"

      - name: Force Unlock Terraform State
        run: terraform force-unlock -force ${{ github.event.inputs.lock_id }}